# Generated by Django 4.2.27 on 2025-12-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_blog_blog_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
