# Generated by Django 4.2.27 on 2025-12-30 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_blog_embedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='embedding',
        ),
    ]
